modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "light_level_description"
version = "${version}"
displayName = "Nuttar's Light Level Description"
authors = "Nuttar, Default_Snowman"
description = '''

'''
#logoFile = ""

[[mixins]]
config = "light_level_description.mixins.json"
